# Generated by Django 2.2.7 on 2019-12-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SquirrelTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X', models.FloatField(help_text='Latitude', max_length=50)),
                ('Y', models.FloatField(help_text='Longitude', max_length=50)),
                ('Unique_Squirrel_ID', models.CharField(help_text='Unique Squirrel Id', max_length=50)),
                ('Shift', models.CharField(choices=[('PM', 'PM'), ('AM', 'AM')], help_text='shift', max_length=50)),
                ('Date', models.DateField(help_text='date')),
                ('Age', models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], help_text='Age', max_length=50, null=True)),
                ('Primary_Fur_Color', models.CharField(choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], help_text='Primary Fur Color', max_length=50, null=True)),
                ('Location', models.CharField(choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground')], help_text='Location', max_length=50, null=True)),
                ('Specific_Location', models.CharField(help_text='Specific Location', max_length=50, null=True)),
                ('Running', models.BooleanField(default=False, help_text='Running?')),
                ('Chasing', models.BooleanField(default=False, help_text='Chasing?')),
                ('Climbing', models.BooleanField(default=False, help_text='Climbing?')),
                ('Eating', models.BooleanField(default=False, help_text='Eating?')),
                ('Foraging', models.BooleanField(default=False, help_text='Foraging?')),
                ('Other_Activities', models.CharField(help_text='Other Activities', max_length=50, null=True)),
                ('Kuks', models.BooleanField(default=False, help_text='Kuks?')),
                ('Quaas', models.BooleanField(default=False, help_text='Quaas?')),
                ('Tail_Flags', models.BooleanField(default=False, help_text='Tail Flags?')),
                ('Tail_Twitches', models.BooleanField(default=False, help_text='Tail Twitches?')),
                ('Approaches', models.BooleanField(default=False, help_text='Approaches?')),
                ('Indifferent', models.BooleanField(default=False, help_text='Indifferent?')),
                ('Runs_From', models.BooleanField(default=False, help_text='Runs From?')),
                ('Other_Interactions', models.CharField(help_text='Others Interactions', max_length=50, null=True)),
                ('Hectare', models.CharField(help_text='Hectare', max_length=50)),
                ('Hectare_Squirrel_Number', models.IntegerField(help_text='Squirrel Number')),
                ('Latlong', models.CharField(help_text='LatLong Point', max_length=50)),
                ('Highlight_Fur_Color', models.CharField(help_text='Highlight Fur Color', max_length=50)),
                ('Color_Note', models.CharField(help_text='Color Note', max_length=50)),
                ('Combination_of_Primary_and_Highlight_Color', models.CharField(help_text='Combination of Primary and Highlight', max_length=50)),
                ('Above_Ground_Sighter_Measurement', models.CharField(help_text='Above Ground Sighter Measurement', max_length=50, null=True)),
                ('Moans', models.BooleanField(default=False, help_text='Moans')),
            ],
        ),
    ]
