# Generated by Django 2.2.7 on 2019-12-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SquirrelFinder', '0003_auto_20191203_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirreltracker',
            name='Approaches',
            field=models.CharField(help_text='Approaches?', max_length=50),
        ),
        migrations.AlterField(
            model_name='squirreltracker',
            name='Chasing',
            field=models.CharField(help_text='Chasing?', max_length=50),
        ),
        migrations.AlterField(
            model_name='squirreltracker',
            name='Climbing',
            field=models.CharField(help_text='Climbing?', max_length=50),
        ),
        migrations.AlterField(
            model_name='squirreltracker',
            name='Eating',
            field=models.CharField(help_text='Eating?', max_length=50),
        ),
        migrations.AlterField(
            model_name='squirreltracker',
            name='Foraging',
            field=models.CharField(help_text='Foraging?', max_length=50),
        ),
        migrations.AlterField(
            model_name='squirreltracker',
            name='Indifferent',
            field=models.CharField(help_text='Indifferent?', max_length=50),
        ),
        migrations.AlterField(
            model_name='squirreltracker',
            name='Kuks',
            field=models.CharField(help_text='Kuks?', max_length=50),
        ),
        migrations.AlterField(
            model_name='squirreltracker',
            name='Moans',
            field=models.CharField(help_text='Moans', max_length=50),
        ),
        migrations.AlterField(
            model_name='squirreltracker',
            name='Quaas',
            field=models.CharField(help_text='Quaas?', max_length=50),
        ),
        migrations.AlterField(
            model_name='squirreltracker',
            name='Running',
            field=models.CharField(help_text='Running?', max_length=50),
        ),
        migrations.AlterField(
            model_name='squirreltracker',
            name='Runs_From',
            field=models.CharField(help_text='Runs From?', max_length=50),
        ),
        migrations.AlterField(
            model_name='squirreltracker',
            name='Tail_Flags',
            field=models.CharField(help_text='Tail Flags?', max_length=50),
        ),
        migrations.AlterField(
            model_name='squirreltracker',
            name='Tail_Twitches',
            field=models.CharField(help_text='Tail Twitches?', max_length=50),
        ),
    ]
