# Generated by Django 2.2.7 on 2019-12-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SquirrelFinder', '0004_auto_20191203_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirreltracker',
            name='Hectare_Squirrel_Number',
            field=models.CharField(help_text='Squirrel Number', max_length=50),
        ),
    ]
