# Generated by Django 2.2.7 on 2019-12-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SquirrelFinder', '0005_auto_20191203_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squirreltracker',
            name='Latlong',
        ),
        migrations.AlterField(
            model_name='squirreltracker',
            name='Date',
            field=models.DateField(help_text='date'),
        ),
        migrations.AlterField(
            model_name='squirreltracker',
            name='Unique_Squirrel_ID',
            field=models.CharField(help_text='Unique Squirrel ID', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='squirreltracker',
            name='X',
            field=models.FloatField(help_text='Longitude'),
        ),
        migrations.AlterField(
            model_name='squirreltracker',
            name='Y',
            field=models.FloatField(help_text='Latitude'),
        ),
    ]
