# Generated by Django 2.2.7 on 2019-12-07 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SquirrelFinder', '0006_auto_20191206_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirreltracker',
            name='Approaches',
            field=models.BooleanField(default=False, help_text='Approaches?'),
        ),
        migrations.AlterField(
            model_name='squirreltracker',
            name='Chasing',
            field=models.BooleanField(default=False, help_text='Chasing?'),
        ),
        migrations.AlterField(
            model_name='squirreltracker',
            name='Climbing',
            field=models.BooleanField(default=False, help_text='Climbing?'),
        ),
        migrations.AlterField(
            model_name='squirreltracker',
            name='Eating',
            field=models.BooleanField(default=False, help_text='Eating?'),
        ),
        migrations.AlterField(
            model_name='squirreltracker',
            name='Foraging',
            field=models.BooleanField(default=False, help_text='Foraging?'),
        ),
        migrations.AlterField(
            model_name='squirreltracker',
            name='Indifferent',
            field=models.BooleanField(default=False, help_text='Indifferent?'),
        ),
        migrations.AlterField(
            model_name='squirreltracker',
            name='Kuks',
            field=models.BooleanField(default=False, help_text='Kuks?'),
        ),
        migrations.AlterField(
            model_name='squirreltracker',
            name='Moans',
            field=models.BooleanField(default=False, help_text='Moans'),
        ),
        migrations.AlterField(
            model_name='squirreltracker',
            name='Quaas',
            field=models.BooleanField(default=False, help_text='Quaas?'),
        ),
        migrations.AlterField(
            model_name='squirreltracker',
            name='Running',
            field=models.BooleanField(default=False, help_text='Running?'),
        ),
        migrations.AlterField(
            model_name='squirreltracker',
            name='Runs_From',
            field=models.BooleanField(default=False, help_text='Runs From?'),
        ),
        migrations.AlterField(
            model_name='squirreltracker',
            name='Tail_Flags',
            field=models.BooleanField(default=False, help_text='Tail Flags?'),
        ),
        migrations.AlterField(
            model_name='squirreltracker',
            name='Tail_Twitches',
            field=models.BooleanField(default=False, help_text='Tail Twitches?'),
        ),
    ]
