# Generated by Django 2.2.7 on 2019-12-08 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SquirrelFinder', '0008_auto_20191206_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squirreltracker',
            name='Above_Ground_Sighter_Measurement',
        ),
        migrations.RemoveField(
            model_name='squirreltracker',
            name='Color_Notes',
        ),
        migrations.RemoveField(
            model_name='squirreltracker',
            name='Combination_of_Primary_and_Highlight_Color',
        ),
        migrations.RemoveField(
            model_name='squirreltracker',
            name='Hectare',
        ),
        migrations.RemoveField(
            model_name='squirreltracker',
            name='Hectare_Squirrel_Number',
        ),
        migrations.RemoveField(
            model_name='squirreltracker',
            name='Highlight_Fur_Color',
        ),
        migrations.RemoveField(
            model_name='squirreltracker',
            name='Other_Interactions',
        ),
    ]
