# Generated by Django 2.2.7 on 2019-12-08 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SquirrelFinder', '0009_auto_20191207_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squirreltracker',
            name='id',
        ),
        migrations.AlterField(
            model_name='squirreltracker',
            name='Unique_Squirrel_ID',
            field=models.CharField(help_text='Unique Squirrel ID', max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
